name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        java: [ '19']
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    name: Java ${{ matrix.Java }} (${{ matrix.os }})

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "./build/libs/ij_vscode_run_config*.jar"
          tag_name: ${{ matrix.java }}-${{ matrix.os }}
