name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        java: [ '19' ]
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    name: Java ${{ matrix.java }} (${{ matrix.os }})

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew buildPlugin

      - name: Version
        run: echo "::set-output name=version::$(./gradlew properties -q | grep "version:" | awk '{print $2}')"
        id: version

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: "build/libs/ij_vscode_run_config*.jar"
          tag_name: ij_vscode_run_config-${{ matrix.Java }}-${{ matrix.os }}
          release_name: ${{ steps.version.outputs.version }}
          prerelease: false
          draft: false

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ij_vscode_run_config-${{ github.run_number }}
          path: "./build/distributions/*.zip"
