name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        java: [ '19' ]
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    name: Java ${{ matrix.java }} (${{ matrix.os }})

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew buildPlugin
      - name: Upload file
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "build/libs/ij_vscode_run_config*.jar"
          tag_name: ${{ matrix.java }}-${{ matrix.os }}
