name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        java: [ '17' ]
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    name: Java ${{ matrix.java }} (${{ matrix.os }})

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew buildPlugin

      - name: Run tests with Gradle
        run: ./gradlew test

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ij_vscode_run_config-${{ matrix.java }}-${{ matrix.os }}
          path: "./build/distributions/*.zip"
